image: golang:latest

variables:
  REPO_NAME: git.home.starkenberg.net/bstarke/hello-go

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/hellogo
  artifacts:
    paths:
      - hellogo

deployment:
  stage: deploy
  script:
    - helm upgrade ${APP_NAME} ./golangweb --install --values=./values.yaml --set image.tag=$IMAGE_TAG --namespace hello
  rules:
    - if: $IMAGE_TAG != null
      when: always